package com.exceptionexamples;

public class Test1 {

    public static void main(String[] args) {

            System.out.println("2");
            int a = 100, b = 0, c;
            c = a / b; //exception occured
            System.out.println(c);
class B{

TRY {
}
}
        } catch (Exception e) {
            System.out.println(e);

        } finally {
            System.out.println("this is finally block");
        }

    }
}







